[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qx-adapters"
version = "0.1.0"
description = "Shims that call legacy code for QuantStack"
authors = [{name = "Jacob"}]
dependencies = [
    "qx-core",
    "qx-data",
    "qx-features",
]

[tool.setuptools.packages.find]
where = ["src"]
