"""SIP Universe Integration for L2 Scalping System

Reads the same daily SIP ticker list used by l2-collector.
"""

import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


def load_daily_sip_symbols(date_str: str | None = None) -> list[str]:
    """Load daily SIP symbols from the same source as l2-collector
    
    If date_str is provided, uses that specific date.
    Otherwise, finds the most recent SIP file (for current trading day).
    """
    
    # Use same path as l2-collector
    sip_dir = Path("/home/jacobw/quantstack/data/daily_sip")
    
    if date_str:
        sip_file = sip_dir / f"sip_universe_{date_str}.txt"
    else:
        # Find most recent SIP file (will be current trading day when markets open)
        sip_files = sorted(sip_dir.glob("sip_universe_*.txt"))
        if not sip_files:
            logger.warning("No SIP universe files found")
            return []
        sip_file = sip_files[-1]
    
    try:
        with open(sip_file) as f:
            symbols = [line.strip() for line in f if line.strip()]
        
        logger.info(f"Loaded {len(symbols)} symbols from {sip_file.name}")
        return symbols
        
    except FileNotFoundError:
        logger.error(f"SIP file not found: {sip_file}")
        return []
    except Exception as e:
        logger.error(f"Error loading SIP symbols: {e}")
        return []


def get_scalping_symbols(max_symbols: int = 3) -> list[str]:
    """Get top symbols for scalping from daily SIP list
    
    Uses most recent SIP file, which will be current trading day's file
    when generated by the daily SIP scheduler.
    
    Raises RuntimeError if no SIP file found - system should not trade
    without a valid SIP universe.
    """
    
    sip_symbols = load_daily_sip_symbols()
    
    if not sip_symbols:
        raise RuntimeError(
            "No SIP universe found! Run daily_sip_scheduler.py before market open. "
            "System will not trade without valid SIP list."
        )
    
    # Take top symbols (SIP list is already ranked by HMM score)
    scalping_symbols = sip_symbols[:max_symbols]
    
    logger.info(f"Selected {len(scalping_symbols)} symbols for scalping: {scalping_symbols}")
    return scalping_symbols
