max_universe_size: 600
min_price: 5.0
max_price: 50.0
min_avg_daily_volume: 10000000.0
min_relative_volume: 0.0
lookback_days: 5
volume_window: 5
exclude_symbols: []
symbols:
- AES
- AMCR
- APA
- APH
- BAC
- BAX
- BEN
- BKR
- CAG
- CCL
- CFG
- CMCSA
- CMG
- CNP
- CPB
- CPRT
- CSCO
- CSX
- CTRA
- CZR
- D
- DAL
- DBC
- DOC
- DVN
- EBAY
- EQT
- EXC
- F
- FAST
- FCX
- FE
- FITB
- FOX
- FOXA
- GEN
- GLW
- GM
- HAL
- HBAN
- HPE
- HPQ
- HRL
- HST
- IBKR
- INTC
- INVH
- IP
- IPG
- IVZ
- KDP
- KEY
- KHC
- KIM
- KMI
- KR
- KVUE
- LKQ
- LNT
- LUV
- LVS
- MGM
- MO
- MOS
- MTCH
- NCLH
- NEM
- NI
- NWS
- NWSA
- PCG
- PFE
- PLTR
- PPL
- RF
- ROL
- SLV
- SMCI
- SYF
- T
- TFC
- TPR
- TSCO
- UAL
- UDR
- UNG
- USB
- VICI
- VST
- VTR
- VTRS
- VZ
- WBD
- WFC
- WMB
- WRB
- WY
